### ISSUE TITLE
The CLI converter collects all diagrams from their names

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#155]
### Describe the bug

If you have more diagrams that share the same name or don't have any names, you get an error during conversion.

### Steps to reproduce

1. Model at least two diagrams with the same name
2. Convert them with the CLI tool
3. Find an error from the conversion

```
java.lang.IllegalStateException: Duplicate key


        at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source)
        at java.util.HashMap.merge(Unknown Source)
        at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
        at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.camunda.community.migration.converter.cli.ConvertEngineCommand.getAllLatestBpmnXml(ConvertEngineCommand.java:64)
...
```

### Expected Behaviour

You get valid conversion results.

### Library version

egal

### Camunda version

egal

### Camunda Distribution

Tomcat

### Other Camunda distribution

egal

**Comment by jonathanlukas** [comment]
The files are collected to a map, which seemed easy. Maybe we will need a list containing a wrapper to have no duplicate sensitivity.
