### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.client.api.response.ActivatedJob.getProcessInstanceKey()" because "this.job" is null

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#16]
This delegate code doesn't work:

```
import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

@Component
public class RejectionNotificationDelegate implements JavaDelegate {

  private static final Logger LOG = LoggerFactory.getLogger(RejectionNotificationDelegate.class);

  public void execute(DelegateExecution execution) throws Exception {
    LOG.info("execute {} of process instance {}", /*execution.getCurrentActivityName()*/ "This should be the task name", execution.getProcessInstanceId());
  }

}
```

Exception stacktrace:
```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.client.api.response.ActivatedJob.getProcessInstanceKey()" because "this.job" is null
	at org.camunda.community.migration.execution.ZeebeJobDelegateExecution.getProcessInstanceId(ZeebeJobDelegateExecution.java:23) ~[camunda-7-adapter-0.1.0.jar:0.1.0]
	at com.camunda.consulting.RejectionNotificationDelegate.execute(RejectionNotificationDelegate.java:15) ~[classes/:na]
	at org.camunda.community.migration.worker.CamundaPlatform7DelegationWorker.delegateToCamundaPlatformCode(CamundaPlatform7DelegationWorker.java:41) ~[camunda-7-adapter-0.1.0.jar:0.1.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at io.camunda.zeebe.spring.client.bean.MethodInfo.invoke(MethodInfo.java:46) ~[spring-zeebe-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.spring.client.jobhandling.JobHandlerInvokingSpringBeans.handle(JobHandlerInvokingSpringBeans.java:42) ~[spring-zeebe-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-8.0.0.jar:8.0.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

It seems to be an issue initializing the [ZeebeJobDelegateExecution](https://github.com/camunda-community-hub/camunda-7-to-8-migration/blob/main/camunda-7-adapter/src/main/java/org/camunda/community/migration/execution/ZeebeJobDelegateExecution.java)

And I don't see any tests in this folder...

**Comment by berndruecker** [comment]
I agree - this is a bug! Well spotted (and I just ignore the well deserved no-tests-elbow comment ;-))

**Comment by berndruecker** [comment]
@ingorichtsmeier I fixed the bug and added a testcase verifying this: https://github.com/camunda-community-hub/camunda-7-to-8-migration/blob/d1af7ebdcde95b14b3adb40094e549ce60675d54/camunda-7-adapter/src/test/java/org/camunda/community/migration/CamundaPlatform7AdapterTest.java#L26
